services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: velara
      POSTGRES_PASSWORD: velara
      POSTGRES_DB: velara
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - velora

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '3070:3070'
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://velara:velara@postgres:5432/velara
    env_file:
      - .env
    networks:
      - velora

  pgcli:
    image: articulate/pgcli:4.4.0
    restart: unless-stopped
    environment:
      TZ: 'Europe/Stockholm'
    depends_on:
      - postgres
    entrypoint: ['pgcli', 'postgresql://velara:velara@postgres:5432/velara']
    tty: true
    stdin_open: true
    networks:
      - velora

volumes:
  postgres_data:

networks:
  velora:
    name: velara
